server:
  port: 8081
spring:
  kafka:
    bootstrapServers: localhost:9092
  application:
    name: ms-yanki-consumer-v1
  data:
    mongodb:
      user: admin
      password: admin
      uri: mongodb://localhost:27017/Bank
